### ISSUE TITLE
Error while testing get_spiked_coverage, get_merged_gr and ScanBamParam

### ISSUE THREAD

**Issue by prisnir-zz** [trichelab/spiky#21]
I was trying out the example provided by you for the function **_get_spiked_coverage_**

- [ ] sb <- system.file("extdata", "example.spike.bam", package="spiky",  mustWork=TRUE)
- [ ] si <- seqinfo_from_header(sb) 
- [ ] genome(si) <- "spike"
- [ ] mgr <- get_merged_gr(si)

> Error in h(simpleError(msg, call)) : 
> error in evaluating the argument 'x' in selecting a method for function 'seqnames': object 'spike' not found

- [ ] fl <- scanBamFlag(isDuplicate=FALSE, isPaired=TRUE, isProperPair=TRUE)
- [ ] bp <- ScanBamParam(flag=fl)

> Error in h(simpleError(msg, call)) : 
>  error in evaluating the argument 'table' in selecting a method for function '%in%': invalid class “PhredQuality” object: undefined class for slot "elementMetadata" ("DataTable_OR_NULL")

Could not test the remaining
bamMapqFilter(bp) <- 20
get_spiked_coverage(sb, bp=bp, gr=mgr)

**Comment by ttriche** [comment]
Interesting, just tried this with a fresh install in a Docker image and it went OK.  I am thinking that we ought to refactor out any and all implicit dependencies on the `spike` data.frame that holds the information about the current set of spikes. 

Just pushed a fix in my repo, testing to see if this fixes the issue in question.  We need to avoid implicit loading of standards.
